#include <windows.h>
#include <sstream>
#include <Tlhelp32.h>
#include <thread>
#include <string>
#include <iostream>
#include <stdio.h>
#include <numbers>
#include <cmath>
#include <limits>
#include <winternl.h>